# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title
# email
baseurl: "/city-analysis" # the subpath of your site, e.g. /blog
url: "madriska.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include:
  - assets

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache
  - tmp/
